//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWWings_DZS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WWWings;
    
    public partial class WWWingsModellContainer : DbContext
    {
        public WWWingsModellContainer()
            : base("name=WWWingsModellContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<Flug> FlugSet { get; set; }
    }
}
